apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uqfzykd1t-python
  janus-idp.io/tekton: uqfzykd1t-python
  backstage.io/kubernetes-id: uqfzykd1t-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uqfzykd1t-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
